version: '3.8'
services:
  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env.production
    ports:
      - "4000:4000"
    restart: always

  web:
    build: ./apps/web
    env_file:
      - ./apps/web/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always